# Generated by Django 5.2.8 on 2025-11-20 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(verbose_name='Ngày làm việc')),
                ('start_time', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('end_time', models.TimeField(verbose_name='Giờ kết thúc')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Đã lên lịch'), ('ACTIVE', 'Đang làm việc'), ('COMPLETED', 'Hoàn thành'), ('CANCELLED', 'Đã hủy')], default='SCHEDULED', max_length=20, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='users.doctor', verbose_name='Bác sĩ')),
            ],
            options={
                'verbose_name': 'Lịch trình bác sĩ',
                'verbose_name_plural': 'Lịch trình bác sĩ',
                'db_table': 'doctor_schedules',
                'ordering': ['-work_date', 'start_time'],
                'unique_together': {('doctor', 'work_date')},
            },
        ),
    ]
