# Generated by Django 5.2.8 on 2025-11-21 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(verbose_name='Ngày khám')),
                ('time_slot', models.CharField(choices=[('08:00-09:00', '08:00 - 09:00'), ('09:00-10:00', '09:00 - 10:00'), ('10:00-11:00', '10:00 - 11:00'), ('11:00-12:00', '11:00 - 12:00'), ('14:00-15:00', '14:00 - 15:00'), ('15:00-16:00', '15:00 - 16:00'), ('16:00-17:00', '16:00 - 17:00'), ('17:00-18:00', '17:00 - 18:00')], max_length=20, verbose_name='Khung giờ khám (1 tiếng)')),
                ('reminder_enabled', models.BooleanField(default=False, verbose_name='Bật nhắc nhở')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Đã đặt lịch'), ('CONFIRMED', 'Đã xác nhận'), ('COMPLETED', 'Hoàn thành'), ('CANCELLED', 'Đã hủy'), ('NO_SHOW', 'Không đến')], default='SCHEDULED', max_length=20, verbose_name='Trạng thái')),
                ('reason', models.TextField(blank=True, verbose_name='Lý do khám')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.doctor', verbose_name='Bác sĩ')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.patient', verbose_name='Bệnh nhân')),
            ],
            options={
                'verbose_name': 'Lịch khám',
                'verbose_name_plural': 'Lịch khám',
                'db_table': 'appointments',
                'ordering': ['-appointment_date', 'time_slot'],
                'unique_together': {('doctor', 'appointment_date', 'time_slot')},
            },
        ),
    ]
