# Generated by Django 4.2.26 on 2025-12-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicFeedbackTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=255)),
                ('score_doctor_attitude', models.CharField(blank=True, max_length=50, null=True)),
                ('score_doctor_clarity', models.CharField(blank=True, max_length=50, null=True)),
                ('score_waiting_time', models.CharField(blank=True, max_length=50, null=True)),
                ('score_procedure_speed', models.CharField(blank=True, max_length=50, null=True)),
                ('score_cleanliness', models.CharField(blank=True, max_length=50, null=True)),
                ('score_staff_attitude', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Chờ xử lý'), ('Finished', 'Đã hoàn thành')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feedback Task',
                'verbose_name_plural': 'Feedback Tasks',
                'db_table': 'clinic_feedback_tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
